services:
  devscape-backend:
    image: aditiaditiaditi/dev-backend:1.0
    ports:
      - 8080:3000
  devscape-frontend:
    image: aditiaditiaditi/dev-frontend:1.0
    ports:
      - 5173:5173
    depends_on:
      devscape-backend:
        condition: service_started